### ISSUE TITLE
biocache-properties creates directories but doesn't change their owner

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-install#172]
``biocache-properties`` creates directories, but doesn't change their owner. For some machines, the owner will be changed by ``biocache-service``, but in the case of the bstore nodes, ``biocache-service`` is not used, so the directories remain only accessible to the root user.

The setting of the owner/permissions was disabled in this commit, but no alternative was introduced for the ``biocache-properties`` role:

https://github.com/AtlasOfLivingAustralia/ala-install/commit/02f2c64381fb966f31c5024360510128105a66ba

**Comment by ansell** [comment]
The result of this is that a biocache load command using jenkins resulted in a wrongful success, with only an error message in the log to indicate that it had infact failed:

```
aws-bstore-1b 2018-05-30 14:36:18,450 INFO : [DataLoader] - SFTP the most recent from sftp://...../dr364
aws-bstore-1b 2018-05-30 14:36:19,099 ERROR: [SFTPTools] - Unable to SCP biocollect/dr364/dr364-20180529-230013.dwc.csv
java.io.IOException: Unable to create directory /data/biocache-load/dr364/biocollect/dr364
	at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:2472)
	at au.org.ala.biocache.util.SFTPTools$.scpFile(SFTPTools.scala:112)
	at au.org.ala.biocache.util.SFTPTools$.sftpLatestArchive(SFTPTools.scala:53)
	at au.org.ala.biocache.load.DataLoader$class.fileDetails$1(DataLoader.scala:430)
	at au.org.ala.biocache.load.DataLoader$class.downloadSFTPArchive(DataLoader.scala:432)
	at au.org.ala.biocache.load.DwcCSVLoader.downloadSFTPArchive(DwcCSVLoader.scala:85)
	at au.org.ala.biocache.load.DataLoader$class.downloadArchive(DataLoader.scala:370)
	at au.org.ala.biocache.load.DwcCSVLoader.downloadArchive(DwcCSVLoader.scala:85)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:111)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:110)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.load.DwcCSVLoader.load(DwcCSVLoader.scala:110)
	at au.org.ala.biocache.load.Loader.load(Loader.scala:202)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:96)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:96)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.Loader$.main(Loader.scala:95)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:133)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
aws-bstore-1b 2018-05-30 14:36:19,105 INFO : [DataLoader] - Unable to extract a new file for dr364 at sftp://...../dr364
aws-bstore-1b 2018-05-30 14:36:19,105 INFO : [DataLoader] - File last modified date: null
aws-bstore-1b 2018-05-30 14:36:19,377 INFO : [DataLoader] - Registry response code: 200
aws-bstore-1b 2018-05-30 14:36:19,377 INFO : [Loader] - Completed loading resource: dr364
Finished: SUCCESS
```
