### ISSUE TITLE
Conflict tomcat8 AntiJARLocking and biocache-service.war in ubuntu 18.04

### ISSUE THREAD

**Issue by santiagomrv** [AtlasOfLivingAustralia/ala-install#336]
```
02-Oct-2019 19:11:05.118 ADVERTENCIA [85.214.89.100-startStop-1] org.apache.catalina.startup.SetContextPropertiesRule.begin [SetContextPropertiesRule]{Context} Setting property 'antiJARLocking' to 'true' did not find a matching property. 02-Oct-2019 19:11:05.119 GRAVE [85.214.89.100-startStop-1] org.apache.tomcat.util.digester.Digester.startElement Begin event threw exception  java.lang.ClassNotFoundException: org.apache.catalina.loader.VirtualWebappLoader 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:116) 	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1250) 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) 	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182) 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339) 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784) 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842) 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) 	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1518) 	at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:531) 	at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:488) 	at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:732) 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:310) 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94) 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:395) 	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:108) 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140) 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754) 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730) 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:980) 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1852) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ansell** [comment]
@santiagomrv We don't currently support biocache-service with tomcat8 due to this issue. If you could set a Pull Request to biocache-service with a fix for the relevant issue it would be great:

https://github.com/AtlasOfLivingAustralia/biocache-service/issues/363

**Comment by brucehyslop** [comment]
the document Biocache Service Starter Pack-v7-20200415_111740.pdf gives instructions that `antiJarLocking` should be removed when running Tomcat8. 

`antiResourceLocking` is a superset of that includes `antiJarLocking` however there are side-effects with setting this property.

> Please note that setting this to true has some side effects, including the disabling of JSP reloading in a running server: see Bugzilla 37668.
>
>Please note that setting this flag to true in applications that are outside the appBase for the Host (the webapps directory by default) will cause the application to be deleted on Tomcat shutdown. You probably don't want to do this, so think twice before setting antiResourceLocking=true on a webapp that's outside the appBase for its Host.

**Comment by ansell** [comment]
@santiagomrv This is fixed in a development snapshot but only tested on Ubuntu-20.04 with Tomcat-9 at this point. Feel free to test biocache-service-2.4-SNAPSHOT (no release for it at this point) on Tomcat-8 + Ubuntu-18.04
