### ISSUE TITLE
Exceptions at parsing verbatimEventData are thrown to console during ingest

### ISSUE THREAD

**Issue by jholetschek** [AtlasOfLivingAustralia/ala-install#75]
During ingest, the following exceptions are thrown - apparently from parsing the verbatimEventDate "9/ 1909". Which is strange for three reasons:
- The space before the year could probably be trimmed, so the parsing would be successful
- We've already parsed the dates and provide them as eventDate (in this case 1909-09), so parsing is not necessary.
- Even if parsing is not possible, exception during this process shouldn't make it to the console, since not all verbatim dates will be parseable.

2015-11-13 12:21:06,182 ERROR: [Consumer] - Error processing record: 'dr7|B 10 0139235',  sleeping for 20 secs before retries
java.lang.NumberFormatException: For input string: " 1919"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:481)
        at java.lang.Integer.parseInt(Integer.java:527)
        at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
        at au.org.ala.biocache.parser.DateParser$.isValid(DateParser.scala:115)
        at au.org.ala.biocache.parser.DateParser$.parseDate(DateParser.scala:28)
        at au.org.ala.biocache.processor.EventProcessor.process(EventProcessor.scala:166)
        at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:99)
        at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:98)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
        at au.org.ala.biocache.processor.Processors$.foreach(Processors.scala:10)
        at au.org.ala.biocache.processor.RecordProcessor.processRecord(RecordProcessor.scala:98)
        at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1$$anonfun$applyOrElse$1.apply(ProcessRecords.scala:326)
        at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1$$anonfun$applyOrElse$1.apply(ProcessRecords.scala:321)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1.applyOrElse(ProcessRecords.scala:321)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at scala.actors.ReactorTask.run(ReactorTask.scala:31)
        at scala.actors.Reactor$class.resumeReceiver(Reactor.scala:129)
        at au.org.ala.biocache.tool.Consumer.scala$actors$InternalReplyReactor$$super$resumeReceiver(ProcessRecords.scala:297)
        at scala.actors.InternalReplyReactor$class.resumeReceiver(InternalReplyReactor.scala:59)
        at au.org.ala.biocache.tool.Consumer.resumeReceiver(ProcessRecords.scala:297)
        at scala.actors.InternalActor$class.searchMailbox(InternalActor.scala:76)
        at au.org.ala.biocache.tool.Consumer.searchMailbox(ProcessRecords.scala:297)
        at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Reactor.scala:117)
        at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:114)
        at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:114)
        at scala.actors.ReactorTask.run(ReactorTask.scala:33)
        at scala.actors.ReactorTask.compute(ReactorTask.scala:63)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-store#121
